#!/bin/bash
#install python dependencies, this is more about deployment
sudo pip install -r requirements.txt
#init migrate needed database data
bash scripts/model-migration
python scripts/provision-create-super-user.py
