#!/bin/bash
#provision database with minimum structure
python manage.py loaddata ddbb/provision-data.json
python manage.py loaddata ddbb/provision-user.json
python manage.py loaddata ddbb/provision-extras.json
