#!/usr/bin/env bash
#install python dependencies, this is more about deployment
sudo pip install -r requirements.txt
python scripts/provision-create-super-user.py
#init migrate needed database data
bash scripts/model-migration
#provision database with minimum structure
python manage.py loaddata ddbb/provision-data.json
