from django.contrib import admin
from upmoodle.models import *

admin.site.register(Level)
admin.site.register(LevelType)
admin.site.register(NoteBoard)
admin.site.register(BannedHash)
admin.site.register(Rol)
admin.site.register(User)
admin.site.register(Calendar)
admin.site.register(CalendarDate)
admin.site.register(CalendarFrequency)
admin.site.register(File)
admin.site.register(FileType)
admin.site.register(Tag)
admin.site.register(Year)
admin.site.register(FileReportList)
admin.site.register(FileComments)
admin.site.register(OkMessage)
admin.site.register(ErrorMessage)
